apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mend-renovate.fullname" . }}-config-js
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  config.js: {{ .Values.renovate.config | quote }}
