{{- if and .Values.renovate.npmrc (not .Values.renovate.npmrcExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mend-renovate.npmrc-secret-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  .npmrc: {{ .Values.renovate.npmrc | b64enc | quote }}
{{- end }}

---

{{- if not .Values.renovate.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mend-renovate.secret-name" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- if .Values.renovate.mendRnvLicenseKey }}
  mendRnvLicenseKey: {{ .Values.renovate.mendRnvLicenseKey | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvGitlabPat }}
  mendRnvGitlabPat: {{ .Values.renovate.mendRnvGitlabPat | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvGithubAppId }}
  mendRnvGithubAppId: {{ .Values.renovate.mendRnvGithubAppId | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvGithubAppKey }}
  mendRnvGithubAppKey: {{ .Values.renovate.mendRnvGithubAppKey | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvBitbucketPat }}
  mendRnvBitbucketPat: {{ .Values.renovate.mendRnvBitbucketPat | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvAdminToken }}
  mendRnvAdminToken: {{ .Values.renovate.mendRnvAdminToken | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.githubComToken }}
  githubComToken: {{ .Values.renovate.githubComToken | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvWebhookSecret }}
  mendRnvWebhookSecret: {{ .Values.renovate.mendRnvWebhookSecret | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.pipIndexUrl }}
  pipIndexUrl: {{ .Values.renovate.pipIndexUrl | b64enc | quote }}
  {{- end}}
  {{- if .Values.renovate.mendRnvServerApiSecret }}
  mendRnvServerApiSecret: {{ .Values.renovate.mendRnvServerApiSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.password }}
  pgPassword: {{ .Values.postgresql.password | b64enc | quote }}
  {{- end }}
{{- end }}
