version: "3.4"

x-controller-shared-variables: &variables-controller
  ## Shared variables - used in both Server and Worker
  MEND_RNV_SERVER_HOSTNAME: http://nginx:4000
  LOG_LEVEL: debug

  ## Mend-Renovate variables. All values must be set!
  ## Note: Can be moved to a separate file (eg. mend.env) and referenced as 'env_file' in both Server and Worker
  # # License Activation
  # MEND_RNV_LICENSE_KEY= # Enterprise licence key. Get License key from Mend.io
  # MEND_RNV_ACCEPT_TOS= # Set to 'Y' to accept Terms of Service
  # MEND_RNV_MC_TOKEN= # Provide token or set to 'auto' to enable Merge Confidence package rules
  # Enable API calls
  # MEND_RNV_ADMIN_API_ENABLED= # Set to 'true' to enable incoming API calls
  # MEND_RNV_SERVER_API_SECRET=abc123 # Must be set when using APIs. Required on Renovate EE Servers.

services:

  # To scale Server and Worker instances post deployment, run the following command (replace values as appropriate):
  # $ docker-compose -f renovate-ee-server-ha-postgres.yml up --scale rnv-ee-server=3 --scale rnv-ee-worker=4 -d --no-recreate

  ## Details for Renovate Server containers
  rnv-ee-server:
    #    restart: unless-stopped
    image: ghcr.io/mend/renovate-ee-server:6.9.1
    deploy:
      replicas: 2
    depends_on:
      - postgres-database
    ports:
      - "8080"
    ## Note: Requires config for a platform (ie. GitHub, GitLab). Insert platform vars in 'environment' section below
    ## Or place platform-specific configuration in a separate env file referenced in the 'env_file' section.
    # env_file:
    #  - env/mend.env  # License activation keys
    #  - env/github.env  # Renovate App connection details
    environment:
      <<: *variables-controller
      LOG_LEVEL: debug
      MEND_RNV_ADMIN_API_ENABLED: false # Set to 'true' to enable incoming API calls
      MEND_RNV_LOG_HISTORY_DIR: /logs   # Must match volume defined in Worker and Server
      MEND_RNV_ENQUEUE_JOBS_ON_STARTUP: disabled  # Options: 'enabled', 'disabled', 'discovered' (default)
      MEND_RNV_DATA_HANDLER_TYPE: postgresql
      PGDATABASE: postgres
      PGUSER: postgres
      PGPASSWORD: password
      PGHOST: postgres-database
      PGPORT: 5432
    volumes:
#      - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version

  rnv-ee-worker:
    #    restart: always
    deploy:
      replicas: 2
    image: ghcr.io/mend/renovate-ee-worker:6.9.1
    depends_on:
      - rnv-ee-server
    env_file:
      - env/mend.env
    environment:
      <<: *variables-controller
    volumes:
#      - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version

  ## Load balancer for Renovate Server containers
  ## Will balance traffic sent to http://localhost:4000/ between Renovate Server instances (rnv-ee-server)
  ## Note! Requires 'nginx.conf' file (available in 'conf' directory).
  nginx:
    image: nginx:1.25.3
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - rnv-ee-server
    ports:
      - "4000:4000"

  ## Postgres Database - used for persisting data held by Mend Renovate about jobs and repos
  postgres-database:
    restart: always
    image: postgres:16.1-alpine3.17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  ## [Optional] Postgres Web Frontend (PGAdmin)
  ## View the database contents via URL: http://localhost:5050/ with user/pwd as defined below
  ## Note! PGAdmin requires 'Dockerfile' file (available in 'docker/pgadmin' directory).
  pgadmin:
    restart: unless-stopped
    build:
      context: dockerfiles/pgadmin
      dockerfile: Dockerfile
    depends_on:
      - postgres-database
    ports:
      - "5050:5050"
    environment:
      - PGADMIN_LISTEN_PORT=5050
