version: "3.4"

x-controller-shared-variables: &variables-controller
  ## Shared variables - used in both Server and Worker
  MEND_RNV_SERVER_HOSTNAME: http://nginx:4000
  LOG_LEVEL: debug

  ## Mend-Renovate variables. All values must be set!
  ## Note: Can be moved to a separate file (eg. mend.env) and referenced as env_file in both Server and Worker
  # Use the env/mend.env file!
  # # Enterprise licence key
  # MEND_RNV_LICENSE_KEY:
  # MEND_RNV_ACCEPT_TOS: Y  # set to 'Y' to accept Terms of Service
  # MEND_RNV_MC_TOKEN: # Set to 'auto' to enable Merge Confidence package rules (Token pinned to #ask-squad-renovate channel)
  # # Enable API calls
  # MEND_RNV_SERVER_API_SECRET: # Must be set when using APIs. Required on Renovate EE Servers.
  # [Server only]
  # MEND_RNV_ADMIN_API_ENABLED: # Set to 'true' to allow incoming API calls.

services:

  # To scale Server and Worker instances post deployment, run the following command (replace values as appropriate):
  # $ docker-compose -f renovate-ee-server-ha-postgres.yml up --scale rnv-ee-server=3 --scale rnv-ee-worker=4 -d --no-recreate

  ## Details for Renovate Server containers
  ## Note: Requires config for a platform (ie. GitHub, GitLab). Insert platform vars here in 'environment' section.
  ## Or place platform-specific configuration in a separate env file and reference it in the 'env_file' section.
  rnv-ee-server:
    #    restart: unless-stopped
    image: ghcr.io/mend/renovate-ee-server:6.9.1
    deploy:
      replicas: 2
    depends_on:
      - postgres-database
    ports:
      - "8080"
    env_file:
      - env/mend.env
      - env/github.env
    environment:
      <<: *variables-controller
      MEND_RNV_LOG_HISTORY_DIR: /logs   # Must match volume defined in Worker and Server
    volumes:
#      - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version

  rnv-ee-worker:
    #    restart: always
    deploy:
      replicas: 2
    image: ghcr.io/mend/renovate-ee-worker:6.9.1
    depends_on:
      - rnv-ee-server
    env_file:
      - env/mend.env
    environment:
      <<: *variables-controller
    volumes:
#      - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version
