apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whitesource-renovate.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
    helm.sh/chart: {{ include "whitesource-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "whitesource-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      securityContext:
{{ toYaml .Values.podSecurityContext | indent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            {{- with .Values.renovate.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.renovate.acceptWhiteSourceTos }}
            - name: ACCEPT_WHITESOURCE_TOS
              value: {{ .Values.renovate.acceptWhiteSourceTos | quote }}
            {{- end }}
            {{- if or .Values.renovate.licenseKey .Values.renovate.existingSecret }}
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: licenseKey
            {{- end }}
            {{- if .Values.renovate.renovatePlatform }}
            - name: RENOVATE_PLATFORM
              value: {{ .Values.renovate.renovatePlatform | quote }}
            {{- end }}
            {{- if .Values.renovate.renovateEndpoint }}
            - name: RENOVATE_ENDPOINT
              value: {{ .Values.renovate.renovateEndpoint | quote }}
            {{- end }}
            {{- if or .Values.renovate.renovateToken .Values.renovate.existingSecret }}
            - name: RENOVATE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: renovateToken
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.githubAppId .Values.renovate.existingSecret }}
            - name: GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: githubAppId
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.githubAppKey .Values.renovate.existingSecret }}
            - name: GITHUB_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: githubAppKey
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.githubComToken .Values.renovate.existingSecret }}
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: githubComToken
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.webhookSecret .Values.renovate.existingSecret }}
            - name: WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: webhookSecret
                  optional: true
            {{- end }}
            {{- if .Values.renovate.schedulerCron }}
            - name: SCHEDULER_CRON
              value: {{ .Values.renovate.schedulerCron | quote }}
            {{- end }}
            {{- if or .Values.renovate.pipIndexUrl .Values.renovate.existingSecret }}
            - name: PIP_INDEX_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "whitesource-renovate.secret-name" . }}
                  key: pipIndexUrl
                  optional: true
            {{- end }}
            {{- if .Values.renovate.noNodeTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            {{- end }}
            {{- if .Values.renovate.noGitTlsVerify }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            {{- end }}
            {{- if .Values.renovate.renovateUserAgent }}
            - name: RENOVATE_USER_AGENT
              value: {{ .Values.renovate.renovateUserAgent | quote }}
            {{- end }}
            {{- if .Values.renovate.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.renovate.logLevel | quote }}
            {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-js-volume
              mountPath: /usr/src/app/config.js
              subPath: config.js
            {{- if .Values.renovate.npmrc }}
            - name: {{ .Release.Name }}-npmrc-volume
              mountPath: /home/ubuntu/.npmrc
              subPath: .npmrc
            {{- end }}
            - name: {{ .Release.Name }}-cache-volume
              mountPath: /tmp/renovate
          {{- if ne (len .Values.extraVolumeMounts) 0 }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 | trim }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-js-volume
          configMap:
            name: {{ .Release.Name }}-config-js
        {{- if or .Values.renovate.npmrc .Values.renovate.npmrcExistingSecret }}
        - name: {{ .Release.Name }}-npmrc-volume
          secret:
            secretName: {{ include "whitesource-renovate.npmrc-secret-name" . }}
        {{- end }}
        - name: {{ .Release.Name }}-cache-volume
          {{- if .Values.cachePersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.cachePersistence.existingClaim | default (printf "%s-cache" (include "whitesource-renovate.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if ne (len .Values.extraVolumes) 0 }}
        {{ toYaml .Values.extraVolumes | nindent 8 | trim }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
