## Load balancer for Renovate Server containers
## Will balance traffic sent to http://localhost:4000/ between Renovate Server instances (rnv-ee-server)
## Note! Requires 'nginx.conf' file (available in 'conf' directory).
services:
  nginx:
    image: nginx:1.25.3
    restart: always
    volumes:
      - ../conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"
