version: "3.4"

## Title: Renovate CE Basic
## Description: This example Docker Compose file starts a single container for Mend Renovate Community Edition.
## Details: Creates 1 x Mend Renovate CE container that acts as Server and Worker. Uses SQLite DB in filesystem.

services:
  renovate-ce:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce
    image: ghcr.io/mend/renovate-ce:X.Y.Z  # Replace X.Y.Z with a specific version number
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    env_file:
      # Import required settings for Mend Renovate Self-hosted
      - ../env/mend-renovate.env # Provide a license key and accept the Terms of Service
      # Choose an env file that matches your Git repository
      - ../env/github.env
      # - ../env/gitlab.env
      # - ../env/bitbucket.env
      # Import optional settings for Renovate CE
      # - ../env/renovate-server-config.env # Set 'MEND_RNV_SERVER_HOSTNAME' to match server container (ie. http://rnv-ee-server:8080)
      # - ../env/renovate-core.env # Set Renovate CLI configuration options. (ie. `RENOVATE_REPOSITORY_CACHE=enabled`)
      # Postgres DB config
      # - ../env/postgres-db.env # Import Postgres config if using PostgreSQL DB
      # MinIO S3 storage
      # - ../env/minio.env
    environment:
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Use 'json' when importing logs to reporting tool (eg. Splunk).
      MEND_RNV_REQUEST_LOGGER_ENABLED: true # Set to 'true' to log all incoming API requests to DEBUG logger. Defaults to 'false'.
      # API settings
      MEND_RNV_ADMIN_API_ENABLED: true # Enable incoming API calls. Must set `MEND_RNV_SERVER_API_SECRET` (Hint: check the mend-renovate.env file).
      MEND_RNV_REPORTING_ENABLED: true # Set to 'true' to enable Reporting APIs. (Set `RENOVATE_REPOSITORY_CACHE` on Worker for PR data)
      # If persisting Job logs or DB, set the following environment variables and enable volume mounts for /logs and /db
      MEND_RNV_LOG_HISTORY_DIR: /logs # Persist Renovate job logs. Enable volume mount for /logs
      MEND_RNV_SQLITE_FILE_PATH: /db/renovate-db.sqlite # Persist database to file. Enable volume mount for /db.
      # Renovate CLI configuration options
      RENOVATE_REPOSITORY_CACHE: enabled # Enable Repo cache to use the /repos/:org(*)/-/:repo/pulls API. Only supported for GitHub.
    volumes:
      # Tip: Create folders in advance to avoid permission issues (ie. when Renovate CLI tries to write logs)
      - /tmp/renovate/job-logs:/logs   # Unix version
      - /tmp/renovate/db:/db
      # - C:\tmp\renovate\job-logs:/logs  # Windows version
      # - C:\tmp\renovate\db:/db
