version: "3.4"

## Title: Renovate Enterprise with SQLite DB
## Description: This example Docker Compose file starts containers for Mend Renovate Enterprise Edition.
## Details: Creates 1 x Server, 2 x Workers. Uses internal SQLite DB.

## Shared variables - used in both Server and Worker
x-shared-variables: &shared-variables
  MEND_RNV_SERVER_HOSTNAME: http://rnv-ee-server:8080

  ## Mend-Renovate essential variables
  MEND_RNV_LICENSE_KEY: # Enterprise licence key. Get License key from Mend.io
  MEND_RNV_ACCEPT_TOS: # Set to 'Y' to accept Terms of Service
  MEND_RNV_SERVER_API_SECRET: abc123 # Required on Server and Worker for internal communication

## Server variables
x-server-variables: &server-variables
  # Enable Merge Confidence package rules
  MEND_RNV_MC_TOKEN: auto # Provide token or set to 'auto' to enable

  # Renovate App connection details (eg. GitHub, GitLab, Bitbucket)
  # GitHub configuration variables provided below for convenience.
  # See Renovate-CE-EE documentation for connection details for all platforms.
  # MEND_RNV_PLATFORM: github
  # MEND_RNV_ENDPOINT: # Required for GitLab or GitHub Enterprise Server; not for GitHub.com. Include the trailing slash.
  # MEND_RNV_GITHUB_APP_ID: # App ID
  # MEND_RNV_GITHUB_APP_KEY: # Private key
  # MEND_RNV_WEBHOOK_SECRET: # Webhook secret (Defaults to 'renovate')

  # Mend Renovate Application settings (Optional)
  # MEND_RNV_ADMIN_API_ENABLED: true  # Enable incoming API calls. Must set MEND_RNV_SERVER_API_SECRET.
  # MEND_RNV_LOG_HISTORY_DIR: /logs  # Persist Renovate job logs - organized by org/rep/timestamp. Enable volume mount!
  # MEND_RNV_SQLITE_FILE_PATH: /db/renovate-ce.sqlite  # Persist database to file. Enable volume mount! (Defaults to '/tmp/database.sqlite')
  # MEND_RNV_ENQUEUE_JOBS_ON_STARTUP: disabled  # Options: 'enabled', 'disabled', 'discovered' (default)
  # MEND_RNV_AUTODISCOVER_FILTER: org1/*, org2/test* # Renovate will only run on these repos

  # Core Renovate settings
  # GITHUB_COM_TOKEN: # Personal Access Token for github.com (used for retrieving changelogs)

services:

  ## Renovate Server
  # Note: Server instances can not scale unless using a network database (eg. Postgres)
  rnv-ee-server:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-server
    image: ghcr.io/mend/renovate-ee-server:<latest-version>
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    environment:
      <<: [*shared-variables, *server-variables]
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'
    volumes:
      # - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version
      - C:\tmp\renovate\db:/db

  ## Renovate Worker
  # To scale Worker instances post deployment, run the following command (replace values as appropriate):
  # $ docker-compose -f <this-file-name>.yml up --scale rnv-ee-worker=4 -d --no-recreate
  rnv-ee-worker:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-worker
    image: ghcr.io/mend/renovate-ee-worker:<latest-version>
    deploy:
      replicas: 2
    depends_on:
      - rnv-ee-server
    environment:
      <<: *shared-variables
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'
    volumes:
      # - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version
