version: "3.4"

## Title: Renovate Enterprise with SQLite DB
## Description: This example Docker Compose file starts containers for Mend Renovate Enterprise Edition.
## Details: Creates 1 x Server, 2 x Workers. Uses internal SQLite DB.

## Shared variables - used in both Server and Worker
x-shared-variables: &shared-variables
  MEND_RNV_SERVER_HOSTNAME: http://rnv-ee-server:8080

  ## Mend-Renovate essential variables
  # MEND_RNV_LICENSE_KEY: # Enterprise licence key. Get License key from Mend.io
  # MEND_RNV_ACCEPT_TOS: # Set to 'Y' to accept Terms of Service
  # MEND_RNV_SERVER_API_SECRET: abc123 # Required on Server and Worker for internal communication

## Server variables
x-server-variables: &server-variables
  # Mend Renovate Application settings (Optional)
  ## APIs
  MEND_RNV_ADMIN_API_ENABLED: true  # Enable incoming API calls. Must set MEND_RNV_SERVER_API_SECRET.
  MEND_RNV_SERVER_API_SECRET: abc123 # Required to enable APIs
  MEND_RNV_REPORTING_ENABLED: true # Defaults to false. Note: Enable RENOVATE_REPOSITORY_CACHE on Worker to activate /pulls API.
  ## Job Logs
  MEND_RNV_LOG_HISTORY_DIR: /logs  # Persist Renovate job logs - organized by org/rep/timestamp. Enable volume mount!
  # MEND_RNV_LOG_HISTORY_S3: s3://job-logs # Define the S3 bucket/folder configuration. Format: s3://<bucket>/dir1/dir2
  # MEND_RNV_LOG_HISTORY_TTL_DAYS: # Defaults to 30.The number of days to save log files
  # MEND_RNV_LOG_HISTORY_CLEANUP_CRON: # Defaults to '0 0 * * *' (every midnight). Deletes files from MEND_RNV_LOG_HISTORY_DIR that are older than MEND_RNV_LOG_HISTORY_TTL_DAYS.

  ## Sync and Scheduling behaviour
  # MEND_RNV_SYNC_ON_STARTUP: false # Defaults to true. Defines if App Sync will be performed when the server starts.
  # MEND_RNV_APP_SYNC_MODE: batch # Options: [bulk],batch. Set to "batch" to process one org at a time. Defaults to "bulk".
  # MEND_RNV_CRON_APP_SYNC: # Defaults to '0 0,4,8,12,16,20 * * *' (every 4 hours, on the hour)
  # MEND_RNV_CRON_JOB_SCHEDULER: # Options: "off","always",{cron} Defaults to '0 * * * *' (hourly)
  MEND_RNV_ENQUEUE_JOBS_ON_STARTUP: disabled  # Options: enabled,disabled,[discovered]
  # MEND_RNV_AUTODISCOVER_FILTER: org1/*, org2/test* # Renovate will only run on these repos
  # MEND_RNV_WORKER_CLEANUP: always # Defines how often to perform file cleanup on Worker containers. Defaults to "off". Values: off, always, (cron. ie. "0 0 * * *" will perform cleanup daily at midnight.)
  # MEND_RNV_WORKER_CLEANUP_DIRS: # Replace the cleanup dirs. Defaults to "/opt/containerbase,/tmp/renovate/cache,/tmp/renovate/repos,/home/ubuntu"

## Worker variables
x-worker-variables: &worker-variables
  # Core Renovate settings
  # GITHUB_COM_TOKEN: # Personal Access Token for github.com (used for retrieving changelogs)
  RENOVATE_REPOSITORY_CACHE: enabled  # Enable Repo cache to use the /repos/:org(*)/-/:repo/pulls API. Only supported for GitHub.

services:

  ## Renovate Server
  # Note: Server instances can not scale unless using a network database (eg. Postgres)
  rnv-ee-server:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-server
    image: ghcr.io/mend/renovate-pro:ee-server-4440fc021f5683ffc7708012c591afd615ef2a21
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      # - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
      - "8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    env_file:
      - ../env/.env.mend-rnv-ee
      - ../env/.env.github-ee
      - ../env/.env.minio
    environment:
      <<: [*shared-variables, *server-variables]
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'
    volumes:
      # - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version
      - C:\tmp\renovate\db:/db

  ## Renovate Worker
  # To scale Worker instances post deployment, run the following command (replace values as appropriate):
  # $ docker-compose -f <this-file-name>.yml up --scale rnv-ee-worker=4 -d --no-recreate
  rnv-ee-worker:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-worker
    image: ghcr.io/mend/renovate-pro:ee-worker-4440fc021f5683ffc7708012c591afd615ef2a21
    deploy:
      replicas: 2
    depends_on:
      - rnv-ee-server
    env_file:
      - ../env/.env.mend-rnv-ee
      - ../env/.env.minio
    environment:
      <<: [*shared-variables, *worker-variables]
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'
    volumes:
      # - /tmp/renovate/job-logs:/logs   # Unix version
      - C:\tmp\renovate\job-logs:/logs  # Windows version
