version: "3.6"

## Title: Renovate CE with SQLite DB
## Description: This example Docker Compose file starts a single container for Mend Renovate Community Edition.
## Details: Creates 1 x Mend Renovate CE container that acts as Server and Worker.

services:
  renovate-ce:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce
    image: ghcr.io/mend/renovate-ce:<latest-version>
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    environment:
      # Optional: Enable debug logging for verbose output
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Useful when importing logs to reporting tool (eg. Splunk).

      # Provide a license key and accept the Terms of Service
      MEND_RNV_LICENSE_KEY: # For a free unrestricted repo Community Edition license key register at https://www.mend.io/renovate-community/
      # Use this key for 10 repos: eyJsaW1pdCI6IjEwIn0=.30440220457941b71ea8eb345c729031718b692169f0ce2cf020095fd328812f4d7d5bc1022022648d1a29e71d486f89f27bdc8754dfd6df0ddda64a23155000a61a105da2a1
      MEND_RNV_ACCEPT_TOS: # Set to 'Y' to accept Terms of Service
      # Provide connection details for the GitHub App
      # Available at: https://github.com/settings/apps/<your-renovate-app>
      MEND_RNV_PLATFORM: github
      MEND_RNV_GITHUB_APP_ID: # App ID
      MEND_RNV_GITHUB_APP_KEY: # Private key
      # MEND_RNV_WEBHOOK_SECRET: # Webhook secret (Defaults to 'renovate')

      # Mend Renovate Application settings (Optional)
      # MEND_RNV_ADMIN_API_ENABLED: true  # Enable incoming API calls. Must set MEND_RNV_SERVER_API_SECRET.
      # MEND_RNV_SERVER_API_SECRET: abc123 # Required to enable APIs
      # MEND_RNV_LOG_HISTORY_DIR: /logs  # Persist Renovate job logs - organized by org/rep/timestamp. Enable volume mount!
      # MEND_RNV_SQLITE_FILE_PATH: /db/renovate-ce.sqlite  # Persist database to file. Enable volume mount! (Defaults to '/tmp/database.sqlite')
      # MEND_RNV_ENQUEUE_JOBS_ON_STARTUP: disabled  # Options: 'enabled', 'disabled', 'discovered' (default)
      # MEND_RNV_AUTODISCOVER_FILTER: org1/*, org2/test* # Renovate will only run on these repos

    # Enable volumes if persisting the application database or Renovate job logs
    # volumes:
    # Tip: Create folders in advance to avoid permission issues (ie. when Renovate CLI tries to write logs)
    #   - /tmp/renovate/job-logs:/logs   # Unix version
    #   - C:\tmp\renovate\job-logs:/logs  # Windows version
    #   - C:\tmp\renovate\db:/db
