version: "3.4"

## Title: Renovate CE Basic
## Description: This example Docker Compose file starts a single container for Mend Renovate Community Edition.
## Details: Creates 1 x Mend Renovate CE container that acts as Server and Worker. Uses SQLite DB in filesystem.

services:
  renovate-ce:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ce
    image: ghcr.io/mend/renovate-ce:<latest-version>
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    env_file:
      # Import required settings for Mend Renovate Self-hosted
      - ../env/mend-renovate.env # Provide a license key and accept the Terms of Service
      # Choose an env file that matches your Git repository
      - ../env/github.env
      # - ../env/gitlab.env
      # - ../env/bitbucket.env
      # Import optional settings for Renovate CE
      - ../env/renovate-server-config.env
    environment:
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Use 'json' when importing logs to reporting tool (eg. Splunk).

    # Enable volumes if persisting the application database or Renovate job logs
    # Tip: Create folders in advance to avoid permission issues (ie. when Renovate CLI tries to write logs)
    # volumes:
    #   - /tmp/renovate/job-logs:/logs   # Unix version
    #   - /tmp/renovate/db:/db
    #   - C:\tmp\renovate\job-logs:/logs  # Windows version
    #   - C:\tmp\renovate\db:/db
