version: "3.6"

## Title: Renovate Enterprise with SQLite DB
## Description: This example Docker Compose file starts containers for Mend Renovate Enterprise Edition.
## Details: Creates 1 x Server, 2 x Workers. Uses internal SQLite DB.

services:

  ## Renovate Server
  # Note: Server instances can not scale unless using a network database (eg. Postgres)
  rnv-ee-server:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-server
    image: ghcr.io/mend/renovate-ee-server:<latest-version>
    ports:
      # Note: Set MEND_RNV_SERVER_PORT to match internal port. (Defaults to 8080)
      - "80:8080"  # "[external]:[internal]" Receive APIs and Webhooks on external port
    env_file:
      # Import required settings for Mend Renovate Self-hosted
      - ../env/mend-renovate.env # Provide a license key and accept the Terms of Service
      # Choose an env file that matches your Git repository
      - ../env/github.env
      # - ../env/gitlab.env
      # - ../env/bitbucket-server.env
      # Import optional settings for Renovate Server
      - ../env/renovate-server-config.env
    environment:
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Use 'json' when importing logs to reporting tool (eg. Splunk).
    # Enable volumes if persisting the application database or Renovate job logs
    # Tip: Create folders in advance to avoid permission issues (ie. when Renovate CLI tries to write logs)
    # volumes:
    #   - /tmp/renovate/job-logs:/logs   # Unix version
    #   - /tmp/renovate/db:/db
    #   - C:\tmp\renovate\job-logs:/logs  # Windows version
    #   - C:\tmp\renovate\db:/db

  ## Renovate Worker
  rnv-ee-worker:
    # Check latest version here: https://github.com/mend/renovate-ce-ee/pkgs/container/renovate-ee-worker
    image: ghcr.io/mend/renovate-ee-worker:<latest-version>
    deploy:
      replicas: 2 # Define the number of Worker containers to run
      # To scale Worker instances post deployment, run the following command (replace values as appropriate):
      # $ docker-compose -f <this-file-name>.yml up --scale rnv-ee-worker=4 -d --no-recreate
    depends_on:
      - rnv-ee-server
    env_file:
      # Import required settings for Mend Renovate Self-hosted
      - ../env/mend-renovate.env
      # Choose an env file that matches your Git repository
      - ../env/github.env
      # - ../env/gitlab.env
      # - ../env/bitbucket-server.env
      # Import settings for Renovate Worker
      - ../env/renovate-worker-config.env # Set 'MEND_RNV_SERVER_HOSTNAME' to match server container (ie. http://rnv-ee-server:8080)
    environment:
      LOG_LEVEL: debug  # Defaults to 'info'
      # LOG_FORMAT: json  # Defaults to 'pretty'. Use 'json' when importing logs to reporting tool (eg. Splunk).
    # volumes:
    #   - /tmp/renovate/job-logs:/logs   # Unix version
    #   - C:\tmp\renovate\job-logs:/logs  # Windows version
