apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mend-renovate.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.renovate.workerReplicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- with .Values.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}-worker
          image: "{{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag }}"
          imagePullPolicy: {{ .Values.workerImage.pullPolicy }}
          env:
            - name:  MEND_RNV_SERVER_HOSTNAME
              value: "http://{{ include "mend-renovate.fullname" . }}"
            {{- if or .Values.renovate.mendRnvServerApiSecret .Values.renovate.existingSecret }}
            - name: MEND_RNV_SERVER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvServerApiSecret
            {{- end }}
            {{- with .Values.renovate.extraWorkerEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            {{- if .Values.renovate.mendRnvAcceptTos }}
            - name: MEND_RNV_ACCEPT_TOS
              value: {{ .Values.renovate.mendRnvAcceptTos | quote }}
            {{- end }}
            {{- if or .Values.renovate.mendRnvLicenseKey .Values.renovate.existingSecret }}
            - name: MEND_RNV_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvLicenseKey
            {{- end }}
            {{- if or .Values.renovate.githubComToken .Values.renovate.existingSecret }}
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: githubComToken
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.pipIndexUrl .Values.renovate.existingSecret }}
            - name: PIP_INDEX_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: pipIndexUrl
                  optional: true
            {{- end }}
            {{- if .Values.renovate.noNodeTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            {{- end }}
            {{- if .Values.renovate.noGitTlsVerify }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            {{- end }}
            {{- if .Values.renovate.renovateUserAgent }}
            - name: RENOVATE_USER_AGENT
              value: {{ .Values.renovate.renovateUserAgent | quote }}
            {{- end }}
            {{- if .Values.renovate.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.renovate.logLevel | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-config-js-volume
              mountPath: /usr/src/app/config.js
              subPath: config.js
            {{- if .Values.renovate.npmrc }}
            - name: {{ .Release.Name }}-npmrc-volume
              mountPath: /home/ubuntu/.npmrc
              subPath: .npmrc
            {{- end }}
            - name: {{ .Release.Name }}-cache-volume
              mountPath: /tmp/renovate
          {{- if ne (len .Values.extraVolumeMounts) 0 }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 | trim }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-js-volume
          configMap:
            name: {{ .Release.Name }}-config-js
        {{- if or .Values.renovate.npmrc .Values.renovate.npmrcExistingSecret }}
        - name: {{ .Release.Name }}-npmrc-volume
          secret:
            secretName: {{ include "mend-renovate.npmrc-secret-name" . }}
        {{- end }}
        - name: {{ .Release.Name }}-cache-volume
          {{- if .Values.cachePersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.cachePersistence.existingClaim | default (printf "%s-cache" (include "mend-renovate.fullname" .)) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
      {{- if ne (len .Values.extraVolumes) 0 }}
        {{ toYaml .Values.extraVolumes | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
