{{- if and .Values.postgresql.enabled .Values.postgresql.development }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mend-renovate.fullname" . }}-database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app: {{ include "mend-renovate.name" . }}-database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ include "mend-renovate.name" . }}-database
    spec:
      containers:
        - name: {{ .Chart.Name }}-postgresql
          image: "{{ .Values.postgresql.development.repository }}:{{ .Values.postgresql.development.tag }}"
          imagePullPolicy: {{ .Values.postgresql.development.pullPolicy }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.user | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgresql.password | quote }}
          ports:
            - name: ee-db
              containerPort: {{ .Values.postgresql.port }}
              protocol: TCP
{{- end }}