apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mend-renovate.fullname" . }}-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app: {{ .Chart.Name }}-server
        {{- with .Values.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.podSecurityContext }}
      securityContext: {{ toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
        - name: {{ .Chart.Name }}-server
          image: "{{ .Values.serverImage.repository }}:{{ .Values.serverImage.tag }}"
          imagePullPolicy: {{ .Values.serverImage.pullPolicy }}
          env:
            {{- if .Values.renovate.mendRnvAcceptTos }}
            - name: MEND_RNV_ACCEPT_TOS
              value: {{ .Values.renovate.mendRnvAcceptTos | quote }}
            {{- end }}
            {{- if or .Values.renovate.mendRnvLicenseKey .Values.renovate.existingSecret }}
            - name: MEND_RNV_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvLicenseKey
            {{- end }}
            {{- if .Values.renovate.mendRnvPlatform }}
            - name: MEND_RNV_PLATFORM
              value: {{ .Values.renovate.mendRnvPlatform | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvEndpoint }}
            - name: MEND_RNV_ENDPOINT
              value: {{ .Values.renovate.mendRnvEndpoint | quote }}
            {{- end }}
            {{- if or .Values.renovate.mendRnvGitlabPat .Values.renovate.existingSecret }}
            - name: MEND_RNV_GITLAB_PAT
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvGitlabPat
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.mendRnvGithubAppId .Values.renovate.existingSecret }}
            - name: MEND_RNV_GITHUB_APP_ID
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvGithubAppId
                  optional: true
            {{- end }}
            {{- if or .Values.renovate.mendRnvGithubAppKey .Values.renovate.existingSecret }}
            - name: MEND_RNV_GITHUB_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvGithubAppKey
                  optional: true
            {{- end }}
            {{- if .Values.renovate.mendRnvSqliteFilePath }}
            - name: MEND_RNV_SQLITE_FILE_PATH
              value: {{ .Values.renovate.mendRnvSqliteFilePath | quote }}
            {{- end }}
            {{- if or .Values.renovate.mendRnvWebhookSecret .Values.renovate.existingSecret }}
            - name: MEND_RNV_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvWebhookSecret
                  optional: true
            {{- end }}
            {{- if .Values.renovate.mendRnvCronJobScheduler }}
            - name: MEND_RNV_CRON_JOB_SCHEDULER
              value: {{ .Values.renovate.mendRnvCronJobScheduler | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvCronAppSync }}
            - name: MEND_RNV_CRON_APP_SYNC
              value: {{ .Values.renovate.mendRnvCronAppSync | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvAutoDiscoverFilter }}
            - name: MEND_RNV_AUTODISCOVER_FILTER
              value: {{ .Values.renovate.mendRnvAutoDiscoverFilter | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvEnqueueJobsOnStartup }}
            - name: MEND_RNV_ENQUEUE_JOBS_ON_STARTUP
              value: {{ .Values.renovate.mendRnvEnqueueJobsOnStartup | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvUserAgent }}
            - name: MEND_RNV_USER_AGENT
              value: {{ .Values.renovate.mendRnvUserAgent | quote }}
            {{- end }}
            {{- if .Values.renovate.logLevel }}
            - name: LOG_LEVEL
              value: {{ .Values.renovate.logLevel | quote }}
            {{- end }}
            {{- if .Values.renovate.mendRnvAdminApiEnabled }}
            - name: MEND_RNV_ADMIN_API_ENABLED
              value: {{ .Values.renovate.mendRnvAdminApiEnabled | quote }}
            {{- end }}
            {{- if or .Values.renovate.mendRnvServerApiSecret .Values.renovate.existingSecret }}
            - name: MEND_RNV_SERVER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.secret-name" . }}
                  key: mendRnvServerApiSecret
            {{- end }}
          ports:
            - name: ee-server
              containerPort: 8080
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Release.Name }}-database-volume
              mountPath: /database
          {{- if ne (len .Values.extraVolumeMounts) 0 }}
            {{ toYaml .Values.extraVolumeMounts | nindent 12 | trim }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Release.Name }}-database-volume
          {{- if .Values.databasePersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.databasePersistence.existingClaim | default (printf "%s-database" (include "mend-renovate.fullname" .)) }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- if ne (len .Values.extraVolumes) 0 }}
        {{ toYaml .Values.extraVolumes | nindent 8 | trim }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
