apiVersion: v1
kind: Service
metadata:
  name: {{ include "mend-renovate.fullname" . }}-svc-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: ee-server
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "mend-renovate.name" . }}-server
