{{- if and .Values.postgresql.enabled .Values.postgresql.development }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mend-renovate.fullname" . }}-srv-database
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    helm.sh/chart: {{ include "mend-renovate.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
  selector:
    app.kubernetes.io/name: {{ include "mend-renovate.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app: {{ include "mend-renovate.name" . }}-database
{{- end }}