{{- $root := . -}}
{{- $base := mustDeepCopy (omit $root.Values.renovateWorker "pools") -}}
{{- $pools := default (list) $root.Values.renovateWorker.pools -}}
{{- if eq (len $pools) 0 -}}
  {{- $pools = list (dict "name" "") -}}
{{- end -}}

{{- range $pool := $pools }}
{{- $renovateWorker := mustMergeOverwrite (mustDeepCopy $base) (mustDeepCopy $pool) }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mend-renovate.fullname" $root }}-worker{{ if $renovateWorker.name }}-{{ $renovateWorker.name }}{{ end }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "mend-renovate.name" $root }}
    helm.sh/chart: {{ include "mend-renovate.chart" $root }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    renovate-worker-pool: {{ default "default" $renovateWorker.name | quote }}
    {{- with $renovateWorker.labels.deployment }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $renovateWorker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mend-renovate.name" $root }}
      app.kubernetes.io/instance: {{ $root.Release.Name }}
      app: {{ include "mend-renovate.name" $root }}-worker
      renovate-worker-pool: {{ default "default" $renovateWorker.name | quote }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mend-renovate.name" $root }}
        app.kubernetes.io/instance: {{ $root.Release.Name }}
        app: {{ include "mend-renovate.name" $root }}-worker
        renovate-worker-pool: {{ default "default" $renovateWorker.name | quote }}
        {{- with $renovateWorker.labels.pods }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config.jsFileConfigMap: {{ include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum }}
        checksum/shardedExtraConfigMaps: {{ include (print $root.Template.BasePath "/extra-configmaps.yaml") $root | sha256sum }}
        checksum/extraConfigMaps: {{ include (print $root.Template.BasePath "/worker-extra-configmaps.yaml") $root | sha256sum }}
        {{- with $renovateWorker.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      automountServiceAccountToken: {{ $renovateWorker.automountServiceAccountToken | default false }}
      {{- with $renovateWorker.podSecurityContext }}
      securityContext: {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $renovateWorker.terminationGracePeriodSeconds }}
      {{- if or $renovateWorker.serviceAccount.create $renovateWorker.serviceAccount.existingName }}
      serviceAccountName: {{ include "mend-renovate.worker-service-account-name-for-pool" (dict "root" $root "worker" $renovateWorker) }}
      {{- end }}
      {{- with $renovateWorker.initContainers }}
      initContainers: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ $root.Chart.Name }}-worker
          image: "{{ $renovateWorker.image.repository }}:{{ $renovateWorker.image.version }}"
          imagePullPolicy: {{ $renovateWorker.image.pullPolicy }}
          {{- with $renovateWorker.containerSecurityContext }}
          securityContext: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if or $renovateWorker.extraEnvFromConfigMaps $renovateWorker.extraEnvFromSecrets }}
          envFrom:
          {{- with $renovateWorker.extraEnvFromConfigMaps }}
            {{- range . }}
            - configMapRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- with $renovateWorker.extraEnvFromSecrets }}
            {{- range . }}
            - secretRef:
                name: {{ .name }}
            {{- end }}
          {{- end }}
          {{- end }}
          env:
            {{- with $renovateWorker.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: MEND_RNV_SERVER_HOSTNAME
              {{- $httpsPort:= "" }}
              {{- $scheme := "http" }}
              {{- if or $renovateWorker.mendRnvClientHttpsConfig $renovateWorker.mendRnvClientHttpsConfigPath}}
                {{- $httpsPort = print ":" $root.Values.service.ports.https }}
                {{- $scheme = "https" }}
              {{- end}}
              value: "{{ $scheme }}://{{ include "mend-renovate.fullname" $root }}-svc-server{{ $httpsPort }}"
            {{- if or $root.Values.renovateServer.mendRnvServerApiSecret $root.Values.renovateServer.existingSecret }}
            - name: MEND_RNV_SERVER_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.server-secret-name" $root }}
                  key: mendRnvServerApiSecret
            {{- end }}

            {{- if $root.Values.license.mendRnvAcceptTos }}
            - name: MEND_RNV_ACCEPT_TOS
              value: {{ $root.Values.license.mendRnvAcceptTos | quote }}
            {{- end }}
            {{- if or $root.Values.license.mendRnvLicenseKey $root.Values.license.existingSecret }}
            - name: MEND_RNV_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.license-secret-name" $root }}
                  key: mendRnvLicenseKey
            {{- end }}
            {{- if $renovateWorker.mendRnvWorkerCleanup }}
            - name: MEND_RNV_WORKER_CLEANUP
              value: {{ $renovateWorker.mendRnvWorkerCleanup | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvWorkerCleanupDirs }}
            - name: MEND_RNV_WORKER_CLEANUP_DIRS
              value: {{ $renovateWorker.mendRnvWorkerCleanupDirs | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvDiskUsageWarnThreshold }}
            - name: MEND_RNV_DISK_USAGE_WARN_THRESHOLD
              value: {{ $renovateWorker.mendRnvDiskUsageWarnThreshold | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvDiskUsageFilter }}
            - name: MEND_RNV_DISK_USAGE_FILTER
              value: {{ $renovateWorker.mendRnvDiskUsageFilter | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvExitInactiveCount }}
            - name: MEND_RNV_EXIT_INACTIVE_COUNT
              value: {{ $renovateWorker.mendRnvExitInactiveCount | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvWorkerNodeArgs }}
            - name: RENOVATE_NODE_ARGS
              value: {{ $renovateWorker.mendRnvWorkerNodeArgs | quote }}
            {{- end }}

            {{- if or $renovateWorker.githubComToken $renovateWorker.existingSecret }}
            - name: GITHUB_COM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.worker-secret-name-for-pool" (dict "root" $root "worker" $renovateWorker) }}
                  key: githubComToken
                  optional: true
            {{- end }}
            {{- if or $renovateWorker.pipIndexUrl $renovateWorker.existingSecret }}
            - name: PIP_INDEX_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "mend-renovate.worker-secret-name-for-pool" (dict "root" $root "worker" $renovateWorker) }}
                  key: pipIndexUrl
                  optional: true
            {{- end }}
            {{- if $renovateWorker.mendRnvWorkerExecutionTimeout }}
            - name: MEND_RNV_WORKER_EXECUTION_TIMEOUT
              value: {{ $renovateWorker.mendRnvWorkerExecutionTimeout | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvDisableGlobalAgent }}
            - name: MEND_RNV_DISABLE_GLOBAL_AGENT
              value: {{ $renovateWorker.mendRnvDisableGlobalAgent | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvEnableHttp2 }}
            - name: MEND_RNV_ENABLE_HTTP2
              value: {{ $renovateWorker.mendRnvEnableHttp2 | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvClientHttpsConfig }}
            - name: MEND_RNV_CLIENT_HTTPS_CONFIG
              value: {{ toJson $renovateWorker.mendRnvClientHttpsConfig | quote }}
            {{- end }}
            {{- if $renovateWorker.mendRnvClientHttpsConfigPath }}
            - name: MEND_RNV_CLIENT_HTTPS_CONFIG_PATH
              value: {{ $renovateWorker.mendRnvClientHttpsConfigPath | quote}}
            {{- end }}
            {{- if $renovateWorker.noNodeTlsVerify }}
            - name: NODE_TLS_REJECT_UNAUTHORIZED
              value: '0'
            {{- end }}
            {{- if $renovateWorker.noGitTlsVerify }}
            - name: GIT_SSL_NO_VERIFY
              value: 'true'
            {{- end }}
            {{- if $renovateWorker.renovateUserAgent }}
            - name: RENOVATE_USER_AGENT
              value: {{ $renovateWorker.renovateUserAgent | quote }}
            {{- end }}
            {{- if $renovateWorker.logLevel }}
            - name: LOG_LEVEL
              value: {{ $renovateWorker.logLevel | quote }}
            {{- end }}
            {{- if $renovateWorker.logFormat }}
            - name: LOG_FORMAT
              value: {{ $renovateWorker.logFormat | quote }}
            {{- end }}
          ports:
            - name: ee-worker
              containerPort: 8080
              protocol: TCP
          {{- with $renovateWorker.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $renovateWorker.readinessProbe }}
          readinessProbe:
          {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $renovateWorker.resources | nindent 12 }}
          volumeMounts:
            - name: {{ $root.Release.Name }}-config-js-volume
              readOnly: true
              mountPath: /usr/src/app/config.js
              subPath: config.js
            {{- if $renovateWorker.npmrc }}
            - name: {{ $root.Release.Name }}-npmrc-volume
              readOnly: true
              mountPath: /home/ubuntu/.npmrc
              subPath: .npmrc
            {{- end }}
            {{- if not $renovateWorker.disableCacheVolume }}
            - name: {{ $root.Release.Name }}-cache-volume
              readOnly: false
              mountPath: /tmp/renovate
            {{- end }}
            {{- with $renovateWorker.extraVolumeMounts }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
      {{- with $renovateWorker.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $renovateWorker.imagePullSecrets }}
      imagePullSecrets:
        - name: {{ $renovateWorker.imagePullSecrets }}
      {{- end }}
      volumes:
        - name: {{ $root.Release.Name }}-config-js-volume
          configMap:
            name: {{ include "mend-renovate.fullname" $root }}-config-js
        {{- if or $renovateWorker.npmrc $renovateWorker.npmrcExistingSecret }}
        - name: {{ $root.Release.Name }}-npmrc-volume
          secret:
            secretName: {{ include "mend-renovate.npmrc-secret-name-for-pool" (dict "root" $root "worker" $renovateWorker) }}
        {{- end }}
        {{- if not $renovateWorker.disableCacheVolume }}
        - name: {{ $root.Release.Name }}-cache-volume
          {{- if $root.Values.dataPersistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ $root.Values.dataPersistence.existingClaim | default (printf "%s-data" (include "mend-renovate.fullname" $root)) }}
          {{- else if $root.Values.dataInMemory.enabled }}
          emptyDir:
            medium: Memory
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- end }}
      {{- with $renovateWorker.extraVolumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $renovateWorker.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $renovateWorker.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
